<?php

namespace App\Services;

use App\Analytics\ReportFilterData;
use Illuminate\Http\Response;
use Symfony\Component\HttpFoundation\StreamedResponse;

class ReportExportService
{
    public function csv(
        string $filename,
        array $columns,
        iterable $rows,
        array $metadata,
        ReportFilterData $filters
    ): StreamedResponse {
        return response()->streamDownload(function () use ($columns, $rows, $metadata, $filters) {
            echo "\xEF\xBB\xBF";
            $handle = fopen('php://output', 'wb');
            foreach ($this->metadataRows($metadata, $filters) as $row) {
                fputcsv($handle, $row);
            }
            fputcsv($handle, []);
            fputcsv($handle, array_values($columns));
            foreach ($rows as $row) {
                $values = (array) $row;
                fputcsv($handle, array_map(
                    fn (string $key) => $this->safe((string) ($values[$key] ?? '')),
                    array_keys($columns)
                ));
            }
            fclose($handle);
        }, $filename, ['Content-Type' => 'text/csv; charset=UTF-8']);
    }

    public function xlsx(
        string $filename,
        array $columns,
        iterable $rows,
        array $metadata,
        ReportFilterData $filters
    ): Response {
        $sheetRows = $this->metadataRows($metadata, $filters);
        $sheetRows[] = [];
        $sheetRows[] = array_values($columns);
        foreach ($rows as $row) {
            $values = (array) $row;
            $sheetRows[] = array_map(
                fn (string $key) => $this->safe((string) ($values[$key] ?? '')),
                array_keys($columns)
            );
        }

        return response($this->workbook($sheetRows), 200, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'Content-Disposition' => 'attachment; filename="'.$filename.'"',
            'Cache-Control' => 'private, no-store, max-age=0',
        ]);
    }

    public function safe(string $value): string
    {
        if ($value === '') {
            return $value;
        }
        if (in_array($value[0], ['=', '@'], true)) {
            return "'".$value;
        }
        if (in_array($value[0], ['+', '-'], true)
            && ! preg_match('/^[+-]\d+(?:\.\d+)?$/', $value)) {
            return "'".$value;
        }

        return $value;
    }

    private function metadataRows(array $metadata, ReportFilterData $filters): array
    {
        return [
            ['Report', $metadata['report_name'] ?? 'Report'],
            ['Company', $metadata['company_name'] ?? ''],
            ['Branches', $metadata['branch_names'] ?? ''],
            ['Period', $filters->dateFrom.' — '.$filters->dateTo],
            ['Currency', $metadata['currency_code'] ?? ''],
            ['Generated at', now()->toIso8601String()],
            ['Generated by', $metadata['generated_by'] ?? ''],
        ];
    }

    private function workbook(array $rows): string
    {
        $sheet = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'.
            '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>';
        foreach ($rows as $rowNumber => $row) {
            $sheet .= '<row r="'.($rowNumber + 1).'">';
            foreach (array_values($row) as $column => $value) {
                $reference = $this->columnName($column + 1).($rowNumber + 1);
                $sheet .= '<c r="'.$reference.'" t="inlineStr"><is><t xml:space="preserve">'.
                    htmlspecialchars((string) $value, ENT_XML1 | ENT_QUOTES, 'UTF-8').
                    '</t></is></c>';
            }
            $sheet .= '</row>';
        }
        $sheet .= '</sheetData></worksheet>';

        return $this->zip([
            '[Content_Types].xml' => '<?xml version="1.0" encoding="UTF-8"?>'.
                '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'.
                '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'.
                '<Default Extension="xml" ContentType="application/xml"/>'.
                '<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'.
                '<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'.
                '</Types>',
            '_rels/.rels' => '<?xml version="1.0" encoding="UTF-8"?>'.
                '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'.
                '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>'.
                '</Relationships>',
            'xl/workbook.xml' => '<?xml version="1.0" encoding="UTF-8"?>'.
                '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '.
                'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'.
                '<sheets><sheet name="Report" sheetId="1" r:id="rId1"/></sheets></workbook>',
            'xl/_rels/workbook.xml.rels' => '<?xml version="1.0" encoding="UTF-8"?>'.
                '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'.
                '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>'.
                '</Relationships>',
            'xl/worksheets/sheet1.xml' => $sheet,
        ]);
    }

    private function zip(array $files): string
    {
        $body = '';
        $central = '';
        $offset = 0;
        foreach ($files as $name => $contents) {
            $compressed = gzdeflate($contents, 9);
            $crc = crc32($contents);
            $nameLength = strlen($name);
            $local = pack(
                'VvvvvvVVVvv',
                0x04034B50,
                20,
                0,
                8,
                0,
                0,
                $crc,
                strlen($compressed),
                strlen($contents),
                $nameLength,
                0
            ).$name.$compressed;
            $central .= pack(
                'VvvvvvvVVVvvvvvVV',
                0x02014B50,
                20,
                20,
                0,
                8,
                0,
                0,
                $crc,
                strlen($compressed),
                strlen($contents),
                $nameLength,
                0,
                0,
                0,
                0,
                0,
                $offset
            ).$name;
            $body .= $local;
            $offset += strlen($local);
        }

        return $body.$central.pack(
            'VvvvvVVv',
            0x06054B50,
            0,
            0,
            count($files),
            count($files),
            strlen($central),
            strlen($body),
            0
        );
    }

    private function columnName(int $index): string
    {
        $name = '';
        while ($index > 0) {
            $index--;
            $name = chr(65 + ($index % 26)).$name;
            $index = intdiv($index, 26);
        }

        return $name;
    }
}
