@extends('layouts.app')
@section('title', $servicePackage->exists ? 'تعديل باقة' : 'إضافة باقة')
@section('page-title', $servicePackage->exists ? 'تعديل باقة' : 'إضافة باقة')
@section('breadcrumb', 'الخدمات / الباقات')
@section('content')
<x-card title="بيانات الباقة وخدماتها"><form class="sw-form" method="POST" action="{{ $servicePackage->exists ? route('service-packages.update',$servicePackage) : route('service-packages.store') }}">@csrf @if($servicePackage->exists)@method('PUT')@endif
<div class="sw-form-grid"><x-form.input name="code" label="الكود (تلقائي عند تركه فارغًا)" :value="old('code',$servicePackage->code)" /><x-form.input name="name" label="الاسم" :value="old('name',$servicePackage->name)" required /><x-form.select name="package_type" label="النوع">@foreach(['fixed','vehicle_size','custom'] as $type)<option value="{{ $type }}" @selected(old('package_type',$servicePackage->package_type)===$type)>{{ $type }}</option>@endforeach</x-form.select><x-form.input type="date" name="start_date" label="البداية" :value="old('start_date',$servicePackage->start_date?->toDateString())" /><x-form.input type="date" name="end_date" label="النهاية" :value="old('end_date',$servicePackage->end_date?->toDateString())" /></div>
<x-form.textarea name="description" label="الوصف">{{ old('description',$servicePackage->description) }}</x-form.textarea>
<h3>الخدمات داخل الباقة</h3>@foreach($services as $service)<label class="sw-check"><input type="checkbox" name="service_ids[]" value="{{ $service->id }}" @checked($servicePackage->exists && $servicePackage->items->contains('service_id',$service->id))><span class="sw-check__box"></span><span>{{ $service->name }}</span></label>@endforeach
<input type="hidden" name="is_active" value="0"><x-form.checkbox name="is_active" label="نشطة" :checked="old('is_active',$servicePackage->exists ? $servicePackage->is_active : true)" />
<div class="sw-form-actions"><x-button type="submit">حفظ الباقة</x-button></div></form></x-card>
@if($servicePackage->exists && auth()->user()->hasPermission('service_packages.manage_prices'))<x-card title="أسعار الفروع والأحجام"><form method="POST" action="{{ route('service-packages.prices.store',$servicePackage) }}" class="sw-form">@csrf<div class="sw-form-grid"><x-form.select name="branch_id" label="الفرع">@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</x-form.select><x-form.select name="vehicle_size_id" label="الحجم"><option value="">عام</option>@foreach($vehicleSizes as $size)<option value="{{ $size->id }}">{{ $size->name }}</option>@endforeach</x-form.select><x-form.input type="number" step="0.0001" name="price" label="السعر" min="0" required /><x-form.input type="number" step="0.0001" name="minimum_price" label="الحد الأدنى" min="0" /><x-form.input type="date" name="effective_from" label="ساري من" :value="now()->toDateString()" required /><x-form.input type="date" name="effective_to" label="ساري حتى" /></div><input type="hidden" name="is_available" value="1"><div class="sw-form-actions"><x-button type="submit">حفظ السعر</x-button></div></form></x-card>@endif
@endsection
