@extends('layouts.app')
@section('title', 'عرض العميل المحتمل')
@section('page-title', $lead->name)
@section('breadcrumb', 'CRM / '.$lead->lead_number)
@section('page-actions')@if(auth()->user()->hasPermission('quotations.create'))<a class="sw-button" href="{{ route('quotations.create',['lead_id'=>$lead->id]) }}">إنشاء عرض سعر</a>@endif @can('update',$lead)<a class="sw-button sw-button--primary" href="{{ route('leads.edit',$lead) }}">تعديل</a>@endcan @endsection
@section('content')
<x-card title="البيانات"><dl class="sw-details-grid"><div><dt>الرقم</dt><dd>{{ $lead->lead_number }}</dd></div><div><dt>الهاتف</dt><dd>{{ $lead->phone }}</dd></div><div><dt>الفرع</dt><dd>{{ $lead->branch->name }}</dd></div><div><dt>المصدر</dt><dd>{{ $lead->source?->name ?? '—' }}</dd></div><div><dt>المسؤول</dt><dd>{{ $lead->assignedUser?->name ?? '—' }}</dd></div><div><dt>الحالة</dt><dd><x-status-badge :status="$lead->status" /></dd></div><div><dt>الأولوية</dt><dd>{{ $lead->priority }}</dd></div><div><dt>المتابعة القادمة</dt><dd>{{ $lead->next_follow_up_at?->format('Y-m-d H:i') ?? '—' }}</dd></div></dl></x-card>
<x-card title="المتابعات"><x-table-shell><thead><tr><th>النوع</th><th>الموعد</th><th>النتيجة</th><th>المتابعة التالية</th></tr></thead><tbody>@forelse($lead->followUps as $followUp)<tr><td>{{ $followUp->follow_up_type }}</td><td>{{ $followUp->scheduled_at?->format('Y-m-d H:i') ?? '—' }}</td><td>{{ $followUp->outcome ?? '—' }}</td><td>{{ $followUp->next_follow_up_at?->format('Y-m-d H:i') ?? '—' }}</td></tr>@empty<tr><td colspan="4">لا توجد متابعات.</td></tr>@endforelse</tbody></x-table-shell>
@if(auth()->user()->hasPermission('leads.follow_up'))<form method="POST" action="{{ route('leads.follow-ups.store',$lead) }}" class="sw-form">@csrf<div class="sw-form-grid"><x-form.select name="follow_up_type" label="النوع" required>@foreach(['call'=>'اتصال','whatsapp'=>'واتساب','email'=>'بريد','visit'=>'زيارة','other'=>'أخرى'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</x-form.select><x-form.input name="scheduled_at" type="datetime-local" label="الموعد" /><x-form.input name="completed_at" type="datetime-local" label="وقت الإكمال" /><x-form.input name="outcome" label="النتيجة" /><x-form.input name="next_follow_up_at" type="datetime-local" label="المتابعة التالية" /><x-form.textarea name="notes" label="ملاحظات"></x-form.textarea></div><x-button type="submit">تسجيل متابعة</x-button></form>@endif</x-card>
@if(!$lead->converted_customer_id && !in_array($lead->status,['lost','cancelled'],true))
    @if(auth()->user()->hasPermission('leads.convert'))<x-card title="تحويل إلى عميل"><form method="POST" action="{{ route('leads.convert',$lead) }}" class="sw-form">@csrf<x-form.select name="customer_id" label="ربط بعميل موجود"><option value="">إنشاء عميل جديد</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->customer_code }} — {{ $customer->name }} @if($customer->normalized_phone === $lead->normalized_phone)(هاتف مطابق)@endif</option>@endforeach</x-form.select><label class="sw-check"><input type="checkbox" name="confirm_duplicate" value="1"> تأكيد إنشاء عميل جديد رغم تطابق محتمل</label><label class="sw-check"><input type="checkbox" name="create_vehicle" value="1"> إنشاء السيارة إن كانت البيانات كافية</label><x-button type="submit">تحويل</x-button></form></x-card>@endif
    @if(auth()->user()->hasPermission('leads.close'))<x-card title="تعليم كـ Lost"><form method="POST" action="{{ route('leads.lost',$lead) }}" class="sw-form">@csrf<x-form.textarea name="lost_reason" label="سبب الخسارة" required></x-form.textarea><x-button type="submit" variant="outline">إغلاق كخسارة</x-button></form></x-card>@endif
@else
<x-card title="نتيجة التحويل"><p>@if($lead->convertedCustomer)تم التحويل إلى <a href="{{ route('customers.show',$lead->convertedCustomer) }}">{{ $lead->convertedCustomer->name }}</a>.@else الحالة: {{ $lead->status }}.@endif</p></x-card>
@endif
@endsection
