@extends('layouts.app')
@section('title',$appointment->exists?'تعديل حجز':'إضافة حجز')
@section('content')
<div class="sw-page-header"><div><h1>{{ $appointment->exists?'تعديل الحجز':'حجز جديد' }}</h1><p>الحجز لا ينشئ أمر عمل أو حركة مخزون.</p></div></div>
<form class="sw-card sw-form" method="POST" action="{{ $appointment->exists?route('appointments.update',$appointment):route('appointments.store') }}">@csrf @if($appointment->exists)@method('PUT')@endif
<div class="sw-form-grid">
<label>الفرع<select name="branch_id">@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected(old('branch_id',$appointment->branch_id)==$branch->id)>{{ $branch->name }}</option>@endforeach</select></label>
<label>العميل<select name="customer_id">@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected(old('customer_id',$appointment->customer_id)==$customer->id)>{{ $customer->name }}</option>@endforeach</select></label>
<label>السيارة<select name="vehicle_id">@foreach($vehicles as $vehicle)<option value="{{ $vehicle->id }}" @selected(old('vehicle_id',$appointment->vehicle_id)==$vehicle->id)>{{ $vehicle->plate_number ?: $vehicle->vin }}</option>@endforeach</select></label>
<label>البداية<input type="datetime-local" name="scheduled_start" value="{{ old('scheduled_start',$appointment->scheduled_start?->format('Y-m-d\\TH:i')) }}" required></label><label>النهاية<input type="datetime-local" name="scheduled_end" value="{{ old('scheduled_end',$appointment->scheduled_end?->format('Y-m-d\\TH:i')) }}" required></label>
<label>الفني<select name="assigned_employee_id"><option value="">إسناد لاحق</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected(old('assigned_employee_id',$appointment->assigned_employee_id)==$employee->id)>{{ $employee->name }}</option>@endforeach</select></label>
<label>المصدر<select name="booking_source">@foreach(['walk_in'=>'حضوري','phone'=>'هاتف','whatsapp'=>'واتساب','website'=>'موقع','other'=>'أخرى'] as $value=>$label)<option value="{{ $value }}" @selected(old('booking_source',$appointment->booking_source??'walk_in')===$value)>{{ $label }}</option>@endforeach</select></label>
<label>الأولوية<select name="priority">@foreach(['low','normal','high','urgent'] as $value)<option value="{{ $value }}" @selected(old('priority',$appointment->priority??'normal')===$value)>{{ $value }}</option>@endforeach</select></label>
<label><input type="hidden" name="deposit_required" value="0"><input type="checkbox" name="deposit_required" value="1" @checked(old('deposit_required',$appointment->deposit_required))> عربون مطلوب</label><label>قيمة العربون<input type="number" step="0.0001" min="0" name="deposit_amount" value="{{ old('deposit_amount',$appointment->deposit_amount??0) }}"></label>
</div>
@php($rows=old('services',$appointment->exists?$appointment->services->toArray():[['quantity'=>1,'estimated_duration_minutes'=>60,'unit_price_snapshot'=>0,'total_snapshot'=>0]]))
@foreach($rows as $i=>$row)<fieldset class="sw-card"><div class="sw-form-grid"><label>الخدمة<select name="services[{{ $i }}][service_id]">@foreach($services as $service)<option value="{{ $service->id }}" @selected(($row['service_id']??null)==$service->id)>{{ $service->name }}</option>@endforeach</select></label><label>الوصف<input name="services[{{ $i }}][description]" value="{{ $row['description']??'' }}" required></label><label>الكمية<input type="number" step="0.000001" name="services[{{ $i }}][quantity]" value="{{ $row['quantity']??1 }}"></label><label>المدة<input type="number" name="services[{{ $i }}][estimated_duration_minutes]" value="{{ $row['estimated_duration_minutes']??60 }}"></label><label>سعر Snapshot<input type="number" step="0.0001" name="services[{{ $i }}][unit_price_snapshot]" value="{{ $row['unit_price_snapshot']??0 }}"></label><label>إجمالي Snapshot<input type="number" step="0.0001" name="services[{{ $i }}][total_snapshot]" value="{{ $row['total_snapshot']??0 }}"></label></div></fieldset>@endforeach
<label>ملاحظات العميل<textarea name="customer_notes">{{ old('customer_notes',$appointment->customer_notes) }}</textarea></label><label>ملاحظات داخلية<textarea name="internal_notes">{{ old('internal_notes',$appointment->internal_notes) }}</textarea></label>
<button class="sw-btn sw-btn--primary">حفظ الحجز</button></form>
@endsection
