@extends('layouts.app')
@section('title',$appointment->appointment_number)
@section('content')
<div class="sw-page-header"><div><h1>{{ $appointment->appointment_number }}</h1><p>{{ $appointment->customer->name }} | {{ $appointment->branch->name }} | {{ $appointment->status }}</p></div>@can('update',$appointment)<a class="sw-btn" href="{{ route('appointments.edit',$appointment) }}">تعديل</a>@endcan</div>
<div class="sw-card"><p>الموعد: {{ $appointment->scheduled_start->format('Y-m-d H:i') }} — {{ $appointment->scheduled_end->format('H:i') }}</p><p>الفني: {{ $appointment->assignedEmployee?->name??'غير مسند' }}</p><p>السيارة: {{ $appointment->vehicle->plate_number ?: $appointment->vehicle->vin }}</p></div>
<div class="sw-card sw-table-wrap"><table class="sw-table"><thead><tr><th>الخدمة</th><th>الكمية</th><th>المدة</th><th>الحالة</th></tr></thead><tbody>@foreach($appointment->services as $item)<tr><td>{{ $item->description }}</td><td>{{ $item->quantity }}</td><td>{{ $item->estimated_duration_minutes }}</td><td>{{ $item->status }}</td></tr>@endforeach</tbody></table></div>
<div class="sw-card"><h2>الإجراءات</h2>@can('confirm',$appointment)<form method="POST" action="{{ route('appointments.confirm',$appointment) }}">@csrf<button class="sw-btn">تأكيد</button></form>@endcan @can('checkIn',$appointment)<form method="POST" action="{{ route('appointments.check-in',$appointment) }}">@csrf<input name="arrival_notes" placeholder="ملاحظات الوصول"><input type="number" name="odometer_snapshot" placeholder="العداد"><button class="sw-btn sw-btn--primary">Check-in</button></form>@endcan @can('cancel',$appointment)<form method="POST" action="{{ route('appointments.cancel',$appointment) }}">@csrf<input name="reason" required placeholder="سبب الإلغاء"><select name="deposit_decision"><option value="pending_decision">قرار العربون لاحقًا</option><option value="refunded">مردود تشغيليًا</option><option value="forfeited">مصادر</option></select><button class="sw-btn">إلغاء</button></form>@endcan</div>
@if(auth()->user()->hasPermission('appointment_deposits.view'))<div class="sw-card"><h2>العربون التشغيلي</h2><p><strong>تنبيه:</strong> هذه السجلات تشغيلية فقط ولا تنشئ صندوقًا أو قيدًا محاسبيًا أو Refund ماليًا.</p>@foreach($appointment->deposits as $deposit)<p>{{ $deposit->receipt_number }} — {{ $deposit->amount }} — {{ $deposit->status }}</p>@endforeach @if(auth()->user()->hasPermission('appointment_deposits.record'))<form method="POST" action="{{ route('appointments.deposits.store',$appointment) }}">@csrf<input type="number" step="0.0001" min="0.0001" name="amount" required><select name="payment_method_id">@foreach($paymentMethods as $method)<option value="{{ $method->id }}">{{ $method->name }}</option>@endforeach</select><input name="reference_number" placeholder="المرجع"><input type="datetime-local" name="received_at" value="{{ now()->format('Y-m-d\\TH:i') }}" required><button class="sw-btn">تسجيل تشغيلي</button></form>@endif</div>@endif
@endsection
