@extends('layouts.app')
@section('title',$workOrder->work_order_number)
@section('breadcrumb','أوامر العمل')
@section('page-title',$workOrder->work_order_number)
@section('content')
<div class="sw-card"><p>{{ $workOrder->customer->name }} — {{ $workOrder->vehicle->plate_number ?: $workOrder->vehicle->vin }} — {{ $workOrder->status }}</p><p>المخزن: {{ $workOrder->warehouse->name }}</p>
@if($workOrder->inspection)<a class="sw-btn" href="{{ route('vehicle-inspections.show',$workOrder->inspection) }}">فحص الاستلام والصور</a>@endif
@if(auth()->user()->hasPermission('work_order_materials.reserve') && in_array($workOrder->status,['inspection_completed','awaiting_materials']))<form method="POST" action="{{ route('work-orders.materials.reserve',$workOrder) }}">@csrf<button class="sw-btn">حجز المواد</button></form>@endif
</div>
@if($workOrder->status === 'awaiting_quality' && auth()->user()->hasPermission('quality_checks.create'))<div class="sw-card"><form method="POST" action="{{ route('quality-checks.start',$workOrder) }}">@csrf<button class="sw-btn">بدء فحص الجودة</button></form></div>@endif
@if($workOrder->status === 'ready_for_delivery' && auth()->user()->hasPermission('work_orders.deliver'))<div class="sw-card"><a class="sw-btn" href="{{ route('deliveries.show',$workOrder) }}">فحص وتسليم السيارة</a></div>@endif
@if($workOrder->status === 'delivered' && auth()->user()->hasPermission('sales_invoices.create'))<div class="sw-card"><form method="POST" action="{{ route('work-orders.invoice',$workOrder) }}">@csrf<button class="sw-btn">إنشاء فاتورة من أمر العمل</button></form></div>@endif
@if($workOrder->qualityChecks->isNotEmpty())<div class="sw-card"><h2>جولات الجودة</h2>@foreach($workOrder->qualityChecks as $check)<p><a href="{{ route('quality-checks.show',$check) }}">{{ $check->quality_check_number }}</a> — {{ $check->status }}</p>@endforeach</div>@endif
@if($workOrder->reworkOrders->isNotEmpty())<div class="sw-card"><h2>إعادة العمل</h2>@foreach($workOrder->reworkOrders as $rework)<p><a href="{{ route('rework-orders.show',$rework) }}">{{ $rework->rework_number }}</a> — {{ $rework->status }}</p>@endforeach</div>@endif
<div class="sw-card"><h2>الخدمات والفنيون</h2>@foreach($workOrder->services as $line)<section><h3>{{ $line->description }} — {{ $line->status }}</h3><p>الفنيون: {{ $line->technicians->pluck('employee.name')->join('، ') ?: 'غير مسند' }}</p>
@if(auth()->user()->hasPermission('work_orders.assign_technicians'))<form method="POST" action="{{ route('work-order-services.technicians.store',$line) }}">@csrf<select name="employee_id">@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->name }}</option>@endforeach</select><select name="role"><option value="technician">فني</option><option value="lead">قائد</option><option value="assistant">مساعد</option></select><input type="number" step="0.0001" name="hourly_cost_snapshot" placeholder="تكلفة الساعة"><button class="sw-btn">تعيين</button></form>@endif
@foreach(['start'=>'بدء','pause'=>'إيقاف مؤقت','resume'=>'استئناف','complete'=>'إكمال'] as $action=>$label)@if(auth()->user()->hasPermission($action==='complete'?'work_orders.complete':($action==='pause'?'work_orders.pause':'work_orders.start')))<form method="POST" action="{{ route('work-order-services.action',[$line,$action]) }}">@csrf<button class="sw-btn">{{ $label }}</button></form>@endif @endforeach
</section>@endforeach</div>
<div class="sw-card sw-table-wrap"><h2>المواد</h2><table class="sw-table"><thead><tr><th>المادة</th><th>المتوقع</th><th>المصروف</th><th>المستخدم</th><th>المرتجع</th><th>الهدر</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>@foreach($workOrder->materials as $material)<tr><td>{{ $material->product?->name }}</td><td>{{ $material->expected_quantity }}</td><td>{{ $material->issued_quantity }}</td><td>{{ $material->used_quantity }}</td><td>{{ $material->returned_quantity }}</td><td>{{ $material->waste_quantity }}</td><td>{{ $material->status }}</td><td>@if(auth()->user()->hasPermission('work_order_materials.issue') && $material->material_type==='quantity')<form method="POST" action="{{ route('work-order-materials.issue',$material) }}">@csrf<input type="number" step="0.000001" name="quantity" value="{{ $material->expected_quantity }}"><button class="sw-btn">صرف</button></form><form method="POST" action="{{ route('work-order-materials.use',$material) }}">@csrf<input type="number" step="0.000001" name="quantity" placeholder="المستخدم"><input type="number" step="0.000001" name="waste_quantity" placeholder="الهدر"><button class="sw-btn">تسجيل الاستخدام</button></form>@endif</td></tr>@endforeach</tbody></table></div>
@can('viewCost',$workOrder)<div class="sw-card"><h2>التكلفة الفعلية</h2><p>مواد: {{ $workOrder->actual_material_cost }} — هدر: {{ $workOrder->actual_waste_cost }} — عمالة: {{ $workOrder->actual_labor_cost }} — الإجمالي: {{ $workOrder->actual_total_cost }} — الهامش: {{ $workOrder->actual_margin }}</p></div>@endcan
<div class="sw-card"><h2>الخط الزمني</h2>@foreach($workOrder->statusLogs as $log)<p>{{ $log->created_at }} — {{ $log->from_status ?: 'created' }} ← {{ $log->to_status }} {{ $log->reason }}</p>@endforeach</div>
@can('cancel',$workOrder)<form class="sw-card" method="POST" action="{{ route('work-orders.cancel',$workOrder) }}">@csrf<input name="reason" required placeholder="سبب الإلغاء"><button class="sw-btn">إلغاء أمر العمل</button></form>@endcan
@endsection
