<?php

return [
    'types' => [
        'customer' => ['label' => 'العملاء', 'scope' => 'branch', 'setup_required' => true],
        'lead' => ['label' => 'العملاء المحتملون', 'scope' => 'branch', 'setup_required' => true],
        'quotation' => ['label' => 'عروض الأسعار', 'scope' => 'branch'],
        'appointment' => ['label' => 'الحجوزات', 'scope' => 'branch'],
        'appointment_deposit' => ['label' => 'دفعات الحجوزات', 'scope' => 'branch'],
        'work_order' => ['label' => 'أوامر العمل', 'scope' => 'branch'],
        'quality_check' => ['label' => 'فحوصات الجودة', 'scope' => 'branch'],
        'rework_order' => ['label' => 'أوامر إعادة العمل', 'scope' => 'branch'],
        'sales_invoice' => ['label' => 'فواتير المبيعات', 'scope' => 'branch'],
        'sales_credit_note' => ['label' => 'إشعارات دائنة للمبيعات', 'scope' => 'branch'],
        'customer_payment' => ['label' => 'مدفوعات العملاء', 'scope' => 'branch'],
        'customer_refund' => ['label' => 'مردودات مدفوعات العملاء', 'scope' => 'branch'],
        'purchase_request' => ['label' => 'طلبات الشراء', 'scope' => 'branch'],
        'purchase_requisition' => ['label' => 'طلبات الاحتياج للشراء', 'scope' => 'branch'],
        'purchase_order' => ['label' => 'أوامر الشراء', 'scope' => 'branch'],
        'goods_receipt' => ['label' => 'استلام المشتريات', 'scope' => 'branch'],
        'purchase_invoice' => ['label' => 'فواتير المشتريات', 'scope' => 'branch'],
        'supplier_invoice' => ['label' => 'فواتير الموردين', 'scope' => 'branch'],
        'purchase_return' => ['label' => 'مرتجعات المشتريات', 'scope' => 'branch'],
        'supplier_credit_note' => ['label' => 'إشعارات دائنة للموردين', 'scope' => 'branch'],
        'supplier' => ['label' => 'الموردون', 'scope' => 'branch'],
        'supplier_payment' => ['label' => 'مدفوعات الموردين', 'scope' => 'branch'],
        'stock_transfer' => ['label' => 'تحويلات المخزون', 'scope' => 'branch'],
        'stock_movement' => ['label' => 'حركات المخزون', 'scope' => 'branch'],
        'stock_opening' => ['label' => 'الأرصدة الافتتاحية للمخزون', 'scope' => 'branch'],
        'stock_adjustment' => ['label' => 'تسويات المخزون', 'scope' => 'branch'],
        'inventory_count' => ['label' => 'جرد المخزون', 'scope' => 'branch'],
        'roll' => ['label' => 'الرولات', 'scope' => 'branch'],
        'roll_scrap' => ['label' => 'قصاصات الرولات', 'scope' => 'branch'],
        'receipt_voucher' => ['label' => 'سندات القبض', 'scope' => 'branch'],
        'payment_voucher' => ['label' => 'سندات الصرف', 'scope' => 'branch'],
        'cash_box_session' => ['label' => 'جلسات الخزائن', 'scope' => 'branch'],
        'cash_receipt' => ['label' => 'المقبوضات النقدية', 'scope' => 'branch'],
        'cash_payment' => ['label' => 'المدفوعات النقدية', 'scope' => 'branch'],
        'treasury_transfer' => ['label' => 'تحويلات الخزينة', 'scope' => 'branch'],
        'merchant_settlement' => ['label' => 'تسويات نقاط البيع', 'scope' => 'branch'],
        'cheque_received' => ['label' => 'الشيكات الواردة', 'scope' => 'branch'],
        'cheque_issued' => ['label' => 'الشيكات الصادرة', 'scope' => 'branch'],
        'bank_adjustment' => ['label' => 'تسويات البنوك', 'scope' => 'mixed'],
        'bank_reconciliation' => ['label' => 'مطابقات البنوك', 'scope' => 'mixed'],
        'warranty' => ['label' => 'الضمانات', 'scope' => 'branch'],
        'warranty_claim' => ['label' => 'مطالبات الضمان', 'scope' => 'branch'],
        'journal_entry' => ['label' => 'القيود اليومية', 'scope' => 'mixed'],
        'opening_balance' => ['label' => 'الأرصدة الافتتاحية المحاسبية', 'scope' => 'mixed'],
        'accounting_closing_run' => ['label' => 'دورات الإقفال المحاسبي', 'scope' => 'company'],
        'expense' => ['label' => 'المصروفات', 'scope' => 'branch'],
        'employee_commission_settlement' => ['label' => 'تسويات عمولات الموظفين', 'scope' => 'branch'],
        'employee_expense_claim' => ['label' => 'مطالبات مصروفات الموظفين', 'scope' => 'branch'],
        'employee_advance' => ['label' => 'سلف الموظفين', 'scope' => 'branch'],
        'product' => ['label' => 'المنتجات', 'scope' => 'branch'],
        'service' => ['label' => 'الخدمات', 'scope' => 'company'],
        'service_package' => ['label' => 'باقات الخدمات', 'scope' => 'company'],
        'promotion' => ['label' => 'العروض الترويجية', 'scope' => 'company'],
    ],
];
