<?php

return [
    [
        'key' => 'main',
        'label' => 'الرئيسية',
        'icon' => 'grid',
        'items' => [
            [
                'label' => 'لوحة التحكم',
                'labels' => ['manager' => 'لوحة الإدارة التنفيذية', 'accountant' => 'لوحة المحاسبة'],
                'icon' => 'grid',
                'route' => 'dashboards.executive',
                'permission' => 'dashboards.executive.view',
                'profiles' => ['manager', 'system_admin'],
            ],
            [
                'label' => 'مؤشرات الفروع',
                'icon' => 'building',
                'route' => 'dashboards.branches',
                'permission' => 'dashboards.branch.view',
                'profiles' => ['manager', 'system_admin'],
            ],
            [
                'label' => 'لوحة المحاسبة',
                'icon' => 'chart',
                'route' => 'accounting.dashboard',
                'permission' => 'accounting.accounts.view',
                'module' => 'accounting',
                'profiles' => ['accountant'],
            ],
            [
                'label' => 'لوحة التحكم',
                'icon' => 'grid',
                'route' => 'dashboard',
                'permission' => 'dashboard.view',
                'profiles' => ['branch_manager', 'generic'],
            ],
        ],
    ],
    [
        'key' => 'sales',
        'label' => 'المبيعات',
        'icon' => 'sales',
        'profiles' => ['branch_manager', 'accountant', 'manager', 'system_admin'],
        'items' => [
            ['label' => 'العملاء', 'icon' => 'users', 'route' => 'customers.index', 'permission' => 'customers.view', 'module' => 'sales', 'profiles' => ['branch_manager', 'manager', 'system_admin']],
            [
                'label' => 'المنتجات والخدمات',
                'icon' => 'box',
                'route' => 'catalog.index',
                'permissions_any' => ['products.view', 'services.view', 'service_packages.view'],
                'module' => 'sales',
                'profiles' => ['branch_manager', 'manager', 'system_admin'],
                'active' => ['catalog.*', 'products.*', 'services.*', 'service-categories.*', 'service-packages.*', 'product-references.*'],
            ],
            ['label' => 'عروض الأسعار', 'icon' => 'sales', 'route' => 'quotations.index', 'permission' => 'quotations.view', 'module' => 'sales', 'profiles' => ['branch_manager', 'manager', 'system_admin']],
            ['label' => 'فواتير المبيعات', 'icon' => 'clipboard', 'route' => 'sales-invoices.index', 'permission' => 'sales_invoices.view', 'module' => 'sales'],
            ['label' => 'تحصيلات العملاء', 'icon' => 'wallet', 'route' => 'customer-payments.index', 'permission' => 'customer_payments.view', 'module' => 'sales'],
            ['label' => 'مرتجعات المبيعات', 'icon' => 'box', 'route' => 'sales-credit-notes.index', 'permission' => 'sales_credit_notes.view', 'module' => 'sales'],
            ['label' => 'أعمار ديون العملاء', 'icon' => 'chart', 'route' => 'sales-reports.aging', 'permission' => 'accounts_receivable.aging', 'module' => 'sales', 'profiles' => ['accountant', 'manager', 'system_admin']],
        ],
    ],
    [
        'key' => 'purchasing_inventory',
        'label' => 'المشتريات والمخزون',
        'icon' => 'box',
        'profiles' => ['branch_manager', 'accountant', 'manager', 'system_admin'],
        'items' => [
            ['label' => 'الموردون', 'icon' => 'users', 'route' => 'suppliers.index', 'permission' => 'suppliers.view', 'module' => 'purchasing'],
            ['label' => 'أوامر الشراء', 'icon' => 'clipboard', 'route' => 'purchase-orders.index', 'permission' => 'purchase_orders.view', 'module' => 'purchasing', 'profiles' => ['branch_manager', 'manager', 'system_admin']],
            ['label' => 'استلام المشتريات', 'icon' => 'box', 'route' => 'goods-receipts.index', 'permission' => 'goods_receipts.view', 'module' => 'purchasing', 'profiles' => ['branch_manager', 'manager', 'system_admin']],
            ['label' => 'فواتير الموردين', 'icon' => 'clipboard', 'route' => 'supplier-invoices.index', 'permission' => 'supplier_invoices.view', 'module' => 'purchasing', 'profiles' => ['accountant', 'manager', 'system_admin']],
            ['label' => 'مدفوعات الموردين', 'icon' => 'wallet', 'route' => 'supplier-payments.index', 'permission' => 'supplier_payments.view', 'module' => 'purchasing', 'profiles' => ['accountant', 'manager', 'system_admin']],
            ['label' => 'مرتجعات المشتريات', 'icon' => 'box', 'route' => 'purchase-returns.index', 'permission' => 'purchase_returns.view', 'module' => 'purchasing', 'profiles' => ['accountant', 'manager', 'system_admin']],
            ['label' => 'إشعارات دائنة للموردين', 'icon' => 'clipboard', 'route' => 'supplier-credit-notes.index', 'permission' => 'supplier_credit_notes.view', 'module' => 'purchasing', 'profiles' => ['accountant', 'manager', 'system_admin']],
            ['label' => 'أعمار ديون الموردين', 'icon' => 'chart', 'route' => 'purchasing-reports.aging', 'permission' => 'accounts_payable.aging', 'module' => 'purchasing', 'profiles' => ['accountant', 'manager', 'system_admin']],
            ['label' => 'المخازن', 'icon' => 'box', 'route' => 'warehouses.index', 'permission' => 'warehouses.view', 'module' => 'basic_inventory', 'profiles' => ['branch_manager', 'manager', 'system_admin']],
            ['label' => 'أرصدة المخزون', 'icon' => 'box', 'route' => 'inventory.index', 'params' => ['balances'], 'permission' => 'inventory.view', 'module' => 'basic_inventory'],
            ['label' => 'حركات المخزون', 'icon' => 'box', 'route' => 'inventory.index', 'params' => ['movements'], 'permission' => 'inventory.view', 'module' => 'basic_inventory', 'profiles' => ['accountant', 'manager', 'system_admin']],
            ['label' => 'الجرد والتسويات', 'icon' => 'clipboard', 'route' => 'inventory.index', 'params' => ['counts'], 'permission' => 'inventory.view', 'module' => 'basic_inventory'],
        ],
    ],
    [
        'key' => 'treasury',
        'label' => 'الخزينة والبنوك',
        'labels' => ['branch_manager' => 'الخزينة اليومية'],
        'icon' => 'wallet',
        'module' => 'treasury',
        'profiles' => ['branch_manager', 'accountant', 'manager', 'system_admin'],
        'items' => [
            ['label' => 'الخزائن', 'icon' => 'wallet', 'route' => 'treasury.cash-boxes.index', 'permission' => 'treasury.cash_boxes.view'],
            ['label' => 'جلسات الخزائن', 'icon' => 'clipboard', 'route' => 'treasury.cash-sessions.index', 'permission' => 'treasury.cash_sessions.view'],
            ['label' => 'المقبوضات النقدية', 'icon' => 'wallet', 'route' => 'treasury.cash-receipts.index', 'permission' => 'treasury.cash_receipts.view', 'profiles' => ['accountant', 'manager', 'system_admin']],
            [
                'label' => 'المدفوعات النقدية',
                'labels' => ['branch_manager' => 'المصروفات والمدفوعات'],
                'icon' => 'wallet',
                'route' => 'treasury.cash-payments.index',
                'permission' => 'treasury.cash_payments.view',
            ],
            ['label' => 'التحويلات', 'icon' => 'wallet', 'route' => 'treasury.transfers.index', 'permission' => 'treasury.transfers.view', 'profiles' => ['accountant', 'manager', 'system_admin']],
            ['label' => 'الشيكات', 'icon' => 'clipboard', 'route' => 'treasury.cheques.received', 'permission' => 'treasury.cheques.view', 'profiles' => ['accountant', 'manager', 'system_admin']],
            ['label' => 'البنوك', 'icon' => 'building', 'route' => 'treasury.banks.index', 'permission' => 'treasury.banks.view', 'profiles' => ['accountant', 'manager', 'system_admin']],
            ['label' => 'الحسابات البنكية', 'icon' => 'building', 'route' => 'treasury.bank-accounts.index', 'permission' => 'treasury.bank_accounts.view', 'profiles' => ['accountant', 'manager', 'system_admin']],
            ['label' => 'التسويات البنكية', 'icon' => 'clipboard', 'route' => 'treasury.reconciliations.index', 'permission' => 'treasury.reconciliations.view', 'profiles' => ['accountant', 'manager', 'system_admin']],
        ],
    ],
    [
        'key' => 'accounting',
        'label' => 'المحاسبة والتقارير',
        'icon' => 'chart',
        'module' => 'accounting',
        'profiles' => ['accountant', 'manager', 'system_admin'],
        'items' => [
            ['label' => 'دليل الحسابات', 'icon' => 'chart', 'route' => 'accounting.accounts.index', 'permission' => 'accounting.accounts.view'],
            ['label' => 'القيود اليومية', 'icon' => 'clipboard', 'route' => 'accounting.journals.index', 'permission' => 'accounting.journals.view'],
            ['label' => 'فترات الترحيل', 'icon' => 'clipboard', 'route' => 'accounting.periods.index', 'permission' => 'accounting.periods.view'],
            ['label' => 'الأرصدة الافتتاحية', 'icon' => 'wallet', 'route' => 'accounting.opening-balances.index', 'permission' => 'accounting.opening_balances.view'],
            ['label' => 'ميزان المراجعة', 'icon' => 'chart', 'route' => 'accounting.reports.trial-balance', 'permission' => 'accounting.trial_balance.view'],
            ['label' => 'الأستاذ العام', 'icon' => 'chart', 'route' => 'accounting.reports.general-ledger', 'permission' => 'accounting.general_ledger.view'],
            ['label' => 'قائمة الدخل', 'icon' => 'chart', 'route' => 'accounting.reports.income-statement', 'permission' => 'accounting.income_statement.view'],
            ['label' => 'الميزانية', 'icon' => 'chart', 'route' => 'accounting.reports.balance-sheet', 'permission' => 'accounting.balance_sheet.view'],
            ['label' => 'التدفقات النقدية', 'icon' => 'chart', 'route' => 'accounting.reports.cash-flow', 'permission' => 'accounting.cash_flow.view'],
        ],
    ],
    [
        'key' => 'financial_settings',
        'label' => 'الإعدادات المالية',
        'icon' => 'settings',
        'module' => 'accounting',
        'profiles' => ['accountant', 'manager', 'system_admin'],
        'items' => [
            ['label' => 'السنوات المالية', 'icon' => 'clipboard', 'route' => 'accounting.fiscal-years.index', 'permission' => 'accounting.fiscal_years.view'],
            ['label' => 'تسلسل المستندات', 'icon' => 'clipboard', 'route' => 'reference.index', 'params' => ['document-sequences'], 'permission' => 'document_sequences.view'],
            ['label' => 'إعدادات المحاسبة', 'icon' => 'settings', 'route' => 'accounting.settings.edit', 'permission' => 'accounting.settings.view'],
            ['label' => 'ربط الحسابات', 'icon' => 'settings', 'route' => 'accounting.mappings.index', 'permissions_any' => ['accounting.mappings.payment_methods', 'accounting.mappings.products']],
        ],
    ],
    [
        'key' => 'administration',
        'label' => 'الإدارة والإعدادات',
        'icon' => 'settings',
        'profiles' => ['manager', 'system_admin'],
        'items' => [
            ['label' => 'بيانات الشركة', 'icon' => 'building', 'route' => 'company.edit', 'permission' => 'companies.view'],
            ['label' => 'الفروع', 'icon' => 'building', 'route' => 'branches.index', 'permission' => 'branches.view'],
            ['label' => 'المستخدمون', 'icon' => 'users', 'route' => 'users.index', 'permission' => 'users.view'],
            ['label' => 'الأدوار والصلاحيات', 'icon' => 'settings', 'route' => 'roles.index', 'permission' => 'roles.view'],
            ['label' => 'الضرائب', 'icon' => 'settings', 'route' => 'reference.index', 'params' => ['taxes'], 'permission' => 'taxes.view'],
            ['label' => 'العملات', 'icon' => 'settings', 'route' => 'reference.index', 'params' => ['currencies'], 'permission' => 'settings.view'],
            ['label' => 'طرق الدفع', 'icon' => 'settings', 'route' => 'reference.index', 'params' => ['payment-methods'], 'permission' => 'payment_methods.view'],
        ],
    ],
];
