<?php

return [
    [
        'key' => 'daily',
        'label' => 'التشغيل اليومي',
        'icon' => 'dashboard',
        'items' => [
            ['label' => 'لوحة التحكم', 'icon' => 'dashboard', 'route' => 'dashboard', 'active' => ['dashboard']],
            ['label' => 'العملاء', 'icon' => 'users', 'route' => 'customers.index', 'permission' => 'customers.view', 'active' => ['customers.*']],
            ['label' => 'السيارات', 'icon' => 'car', 'route' => 'vehicles.index', 'permission' => 'vehicles.view', 'active' => ['vehicles.*']],
            ['label' => 'العملاء المحتملون', 'icon' => 'sales', 'route' => 'leads.index', 'permission' => 'leads.view', 'active' => ['leads.*']],
            ['label' => 'عروض الأسعار', 'icon' => 'sales', 'route' => 'quotations.index', 'permission' => 'quotations.view', 'active' => ['quotations.*']],
            ['label' => 'الحجوزات', 'icon' => 'clipboard', 'route' => 'appointments.index', 'permission' => 'appointments.view', 'active' => ['appointments.index', 'appointments.show', 'appointments.create', 'appointments.edit']],
            ['label' => 'تقويم الحجوزات', 'icon' => 'clock', 'route' => 'appointments.calendar', 'permission' => 'appointments.calendar', 'active' => ['appointments.calendar']],
            ['label' => 'أوامر العمل', 'icon' => 'clipboard', 'route' => 'work-orders.index', 'permission' => 'work_orders.view', 'active' => ['work-orders.*', 'work-order-services.*', 'vehicle-inspections.*']],
            ['label' => 'فحص الجودة', 'icon' => 'clipboard', 'route' => 'quality-checks.index', 'permission' => 'quality_checks.view', 'active' => ['quality-checks.*', 'quality-templates.*']],
            ['label' => 'إعادة العمل', 'icon' => 'wrench', 'route' => 'rework-orders.index', 'permission' => 'rework_orders.view', 'active' => ['rework-orders.*']],
            ['label' => 'تسليم السيارات', 'icon' => 'car', 'route' => 'deliveries.index', 'permission' => 'work_orders.deliver', 'active' => ['deliveries.*']],
            ['label' => 'الضمانات', 'icon' => 'clipboard', 'route' => 'warranties.index', 'permission' => 'warranties.view', 'active' => ['warranties.*']],
            ['label' => 'مطالبات الضمان', 'icon' => 'clipboard', 'route' => 'warranty-claims.index', 'permission' => 'warranty_claims.view', 'active' => ['warranty-claims.*']],
            ['label' => 'فواتير المبيعات', 'icon' => 'sales', 'route' => 'sales-invoices.index', 'permission' => 'sales_invoices.view', 'active' => ['sales-invoices.*']],
            ['label' => 'استلام المدفوعات', 'icon' => 'wallet', 'route' => 'customer-payments.index', 'permission' => 'customer_payments.view', 'active' => ['customer-payments.*']],
            ['label' => 'مرتجعات المبيعات', 'icon' => 'clipboard', 'route' => 'sales-credit-notes.index', 'permission' => 'sales_credit_notes.view', 'active' => ['sales-credit-notes.*']],
            ['label' => 'المبالغ المستردة', 'icon' => 'wallet', 'route' => 'customer-refunds.index', 'permission' => 'customer_refunds.view', 'active' => ['customer-refunds.*']],
            ['label' => 'جلسات الخزائن والجرد', 'icon' => 'clock', 'route' => 'treasury.cash-sessions.index', 'permission' => 'treasury.cash_sessions.view', 'active' => ['treasury.cash-sessions.*', 'treasury.cash-counts.*']],
            ['label' => 'المقبوضات النقدية', 'icon' => 'wallet', 'route' => 'treasury.cash-receipts.index', 'permission' => 'treasury.cash_receipts.view', 'active' => ['treasury.cash-receipts.*']],
            ['label' => 'المدفوعات النقدية', 'icon' => 'wallet', 'route' => 'treasury.cash-payments.index', 'permission' => 'treasury.cash_payments.view', 'active' => ['treasury.cash-payments.*']],
        ],
    ],
    [
        'key' => 'inventory',
        'label' => 'المخزون والمشتريات',
        'icon' => 'box',
        'items' => [
            [
                'label' => 'المنتجات والخدمات',
                'icon' => 'box',
                'route' => 'catalog.index',
                'permissions_any' => ['products.view', 'services.view', 'service_categories.view', 'service_packages.view'],
                'active' => ['catalog.*', 'products.*', 'services.*', 'service-categories.*', 'service-packages.*', 'product-references.*'],
            ],
            ['label' => 'العروض الترويجية', 'icon' => 'sales', 'route' => 'promotions.index', 'permission' => 'promotions.view', 'active' => ['promotions.*']],
            ['label' => 'الموردون', 'icon' => 'users', 'route' => 'suppliers.index', 'permission' => 'suppliers.view', 'active' => ['suppliers.*']],
            ['label' => 'طلبات الشراء', 'icon' => 'clipboard', 'route' => 'purchase-requisitions.index', 'permission' => 'purchase_requisitions.view', 'active' => ['purchase-requisitions.*']],
            ['label' => 'أوامر الشراء', 'icon' => 'cart', 'route' => 'purchase-orders.index', 'permission' => 'purchase_orders.view', 'active' => ['purchase-orders.*']],
            ['label' => 'استلام المشتريات', 'icon' => 'box', 'route' => 'goods-receipts.index', 'permission' => 'goods_receipts.view', 'active' => ['goods-receipts.*']],
            ['label' => 'فواتير الموردين', 'icon' => 'clipboard', 'route' => 'supplier-invoices.index', 'permission' => 'supplier_invoices.view', 'active' => ['supplier-invoices.*']],
            ['label' => 'دفعات الموردين', 'icon' => 'wallet', 'route' => 'supplier-payments.index', 'permission' => 'supplier_payments.view', 'active' => ['supplier-payments.*']],
            ['label' => 'مرتجعات المشتريات', 'icon' => 'box', 'route' => 'purchase-returns.index', 'permission' => 'purchase_returns.view', 'active' => ['purchase-returns.*']],
            ['label' => 'إشعارات الموردين الدائنة', 'icon' => 'clipboard', 'route' => 'supplier-credit-notes.index', 'permission' => 'supplier_credit_notes.view', 'active' => ['supplier-credit-notes.*']],
            ['label' => 'المخازن', 'icon' => 'box', 'route' => 'warehouses.index', 'permission' => 'warehouses.view', 'active' => ['warehouses.*']],
            ['label' => 'تحويلات المخزون', 'icon' => 'box', 'route' => 'stock-transfers.index', 'permission' => 'stock_transfers.view', 'active' => ['stock-transfers.*']],
            ['label' => 'أرصدة المخزون', 'icon' => 'box', 'route' => 'inventory.index', 'params' => ['balances'], 'permission' => 'inventory.view', 'active' => ['inventory.*'], 'active_param' => ['section', 'balances']],
            ['label' => 'حركات المخزون', 'icon' => 'box', 'route' => 'inventory.index', 'params' => ['movements'], 'permission' => 'inventory.view', 'active' => ['inventory.*'], 'active_param' => ['section', 'movements']],
            ['label' => 'الرولات', 'icon' => 'box', 'route' => 'inventory.index', 'params' => ['rolls'], 'permission' => 'inventory.view', 'active' => ['inventory.*'], 'active_param' => ['section', 'rolls']],
            ['label' => 'القصاصات', 'icon' => 'box', 'route' => 'inventory.index', 'params' => ['scraps'], 'permission' => 'inventory.view', 'active' => ['inventory.*'], 'active_param' => ['section', 'scraps']],
            ['label' => 'الرصيد الافتتاحي للمخزون', 'icon' => 'box', 'route' => 'inventory.index', 'params' => ['openings'], 'permission' => 'inventory.view', 'active' => ['inventory.*'], 'active_param' => ['section', 'openings']],
            ['label' => 'تسويات المخزون', 'icon' => 'box', 'route' => 'inventory.index', 'params' => ['adjustments'], 'permission' => 'inventory.view', 'active' => ['inventory.*'], 'active_param' => ['section', 'adjustments']],
            ['label' => 'الجرد', 'icon' => 'clipboard', 'route' => 'inventory.index', 'params' => ['counts'], 'permission' => 'inventory.view', 'active' => ['inventory.*'], 'active_param' => ['section', 'counts']],
            ['label' => 'تنبيهات المخزون', 'icon' => 'alert', 'route' => 'inventory.index', 'params' => ['alerts'], 'permission' => 'inventory.view', 'active' => ['inventory.*'], 'active_param' => ['section', 'alerts']],
        ],
    ],
    [
        'key' => 'finance',
        'label' => 'المالية والمحاسبة',
        'icon' => 'wallet',
        'items' => [
            ['label' => 'نظرة عامة محاسبية', 'icon' => 'wallet', 'route' => 'accounting.dashboard', 'permission' => 'accounting.accounts.view', 'active' => ['accounting.dashboard']],
            ['label' => 'دليل الحسابات', 'icon' => 'chart', 'route' => 'accounting.accounts.index', 'permission' => 'accounting.accounts.view', 'active' => ['accounting.accounts.*']],
            ['label' => 'القيود اليومية', 'icon' => 'clipboard', 'route' => 'accounting.journals.index', 'permission' => 'accounting.journals.view', 'active' => ['accounting.journals.*']],
            ['label' => 'الترحيل المحاسبي', 'icon' => 'wallet', 'route' => 'accounting.posting.index', 'permission' => 'accounting.posting.execute', 'active' => ['accounting.posting.*']],
            ['label' => 'الفترات المحاسبية', 'icon' => 'clock', 'route' => 'accounting.periods.index', 'permission' => 'accounting.periods.view', 'active' => ['accounting.periods.*']],
            ['label' => 'مراكز التكلفة', 'icon' => 'building', 'route' => 'accounting.cost-centers.index', 'permission' => 'accounting.cost_centers.view', 'active' => ['accounting.cost-centers.*']],
            ['label' => 'مالية الموظفين', 'icon' => 'users', 'route' => 'employee-finance.index', 'permission' => 'employees.view', 'active' => ['employee-finance.*']],
            ['label' => 'نظرة عامة للخزينة', 'icon' => 'wallet', 'route' => 'treasury.dashboard', 'permission' => 'treasury.balances.view', 'active' => ['treasury.dashboard']],
            ['label' => 'البنوك', 'icon' => 'building', 'route' => 'treasury.banks.index', 'permission' => 'treasury.banks.view', 'active' => ['treasury.banks.*']],
            ['label' => 'الحسابات البنكية', 'icon' => 'wallet', 'route' => 'treasury.bank-accounts.index', 'permission' => 'treasury.bank_accounts.view', 'active' => ['treasury.bank-accounts.*']],
            ['label' => 'الخزائن وأمناؤها', 'icon' => 'wallet', 'route' => 'treasury.cash-boxes.index', 'permission' => 'treasury.cash_boxes.view', 'active' => ['treasury.cash-boxes.*']],
            ['label' => 'التحويلات', 'icon' => 'wallet', 'route' => 'treasury.transfers.index', 'permission' => 'treasury.transfers.view', 'active' => ['treasury.transfers.*']],
            ['label' => 'كشوف الحساب والاستيراد', 'icon' => 'clipboard', 'route' => 'treasury.bank-statements.index', 'permission' => 'treasury.bank_statements.view', 'active' => ['treasury.bank-statements.*']],
            ['label' => 'جلسات المطابقة', 'icon' => 'chart', 'route' => 'treasury.reconciliations.index', 'permission' => 'treasury.reconciliation.view', 'active' => ['treasury.reconciliations.index', 'treasury.reconciliations.show']],
            ['label' => 'تسويات البنك', 'icon' => 'clipboard', 'route' => 'treasury.bank-adjustments.index', 'permission' => 'treasury.bank_adjustments.view', 'active' => ['treasury.bank-adjustments.*']],
            ['label' => 'الشيكات الواردة', 'icon' => 'clipboard', 'route' => 'treasury.cheques.received', 'permission' => 'treasury.cheques.view', 'active' => ['treasury.cheques.received']],
            ['label' => 'الشيكات الصادرة', 'icon' => 'clipboard', 'route' => 'treasury.cheques.issued', 'permission' => 'treasury.cheques.view', 'active' => ['treasury.cheques.issued']],
            ['label' => 'تسويات نقاط البيع', 'icon' => 'wallet', 'route' => 'treasury.merchant-settlements.index', 'permission' => 'treasury.merchant_settlements.view', 'active' => ['treasury.merchant-settlements.*']],
        ],
    ],
    [
        'key' => 'reports',
        'label' => 'التقارير والإقفالات',
        'icon' => 'chart',
        'items' => [
            ['label' => 'المؤشرات التنفيذية', 'icon' => 'chart', 'route' => 'dashboards.executive', 'permission' => 'dashboards.executive.view', 'active' => ['dashboards.executive']],
            ['label' => 'مؤشرات الفروع', 'icon' => 'building', 'route' => 'dashboards.branches', 'permission' => 'dashboards.branch.view', 'active' => ['dashboards.branches']],
            ['label' => 'مركز التقارير', 'icon' => 'chart', 'route' => 'analytics.reports.show', 'report_center' => true, 'active' => ['analytics.reports.*']],
            ['label' => 'تقارير الاعتمادات', 'icon' => 'chart', 'route' => 'approvals.reports', 'permission' => 'approvals.view', 'active' => ['approvals.reports']],
            ['label' => 'أعمار ديون العملاء', 'icon' => 'chart', 'route' => 'sales-reports.aging', 'permission' => 'accounts_receivable.aging', 'active' => ['sales-reports.*']],
            ['label' => 'أعمار ديون الموردين', 'icon' => 'chart', 'route' => 'purchasing-reports.aging', 'permission' => 'accounts_payable.aging', 'active' => ['purchasing-reports.*']],
            ['label' => 'الأستاذ العام', 'icon' => 'chart', 'route' => 'accounting.reports.general-ledger', 'permission' => 'accounting.general_ledger.view', 'active' => ['accounting.reports.general-ledger']],
            ['label' => 'استعلام القيود', 'icon' => 'clipboard', 'route' => 'accounting.reports.general-journal', 'permission' => 'accounting.general_journal.view', 'active' => ['accounting.reports.general-journal']],
            ['label' => 'ميزان المراجعة', 'icon' => 'chart', 'route' => 'accounting.reports.trial-balance', 'permission' => 'accounting.trial_balance.view', 'active' => ['accounting.reports.trial-balance']],
            ['label' => 'قائمة الدخل', 'icon' => 'wallet', 'route' => 'accounting.reports.income-statement', 'permission' => 'accounting.income_statement.view', 'active' => ['accounting.reports.income-statement']],
            ['label' => 'الميزانية العمومية', 'icon' => 'wallet', 'route' => 'accounting.reports.balance-sheet', 'permission' => 'accounting.balance_sheet.view', 'active' => ['accounting.reports.balance-sheet']],
            ['label' => 'التدفقات النقدية', 'icon' => 'wallet', 'route' => 'accounting.reports.cash-flow', 'permission' => 'accounting.cash_flow.view', 'active' => ['accounting.reports.cash-flow']],
            ['label' => 'تقارير مراكز التكلفة', 'icon' => 'building', 'route' => 'accounting.reports.cost-centers', 'permission' => 'accounting.cost_center_reports.view', 'active' => ['accounting.reports.cost-centers']],
            ['label' => 'تقارير الفروع', 'icon' => 'building', 'route' => 'accounting.reports.branches', 'permission' => 'accounting.branch_reports.view', 'active' => ['accounting.reports.branches']],
            ['label' => 'المستندات غير المرحلة', 'icon' => 'clipboard', 'route' => 'accounting.reports.unposted-sources', 'permission' => 'accounting.unposted_sources.view', 'active' => ['accounting.reports.unposted-sources']],
            ['label' => 'تقارير عمليات الخزينة', 'icon' => 'chart', 'route' => 'treasury.operation-reports', 'permission' => 'treasury.reports.view', 'active' => ['treasury.operation-reports']],
            ['label' => 'تقارير المطابقة', 'icon' => 'chart', 'route' => 'treasury.reconciliations.reports', 'permission' => 'treasury.reconciliation.view', 'active' => ['treasury.reconciliations.reports']],
            ['label' => 'الإقفال المحاسبي', 'icon' => 'lock', 'route' => 'accounting.closing.index', 'permission' => 'accounting.closing.view', 'active' => ['accounting.closing.*']],
        ],
    ],
    [
        'key' => 'administration',
        'label' => 'الإدارة والتحكم',
        'icon' => 'users',
        'items' => [
            ['label' => 'بيانات الشركة', 'icon' => 'building', 'route' => 'company.edit', 'permission' => 'companies.view', 'active' => ['company.*']],
            ['label' => 'الفروع', 'icon' => 'building', 'route' => 'branches.index', 'permission' => 'branches.view', 'active' => ['branches.*']],
            ['label' => 'المستخدمون', 'icon' => 'users', 'route' => 'users.index', 'permission' => 'users.view', 'active' => ['users.*']],
            ['label' => 'الأدوار والصلاحيات', 'icon' => 'settings', 'route' => 'roles.index', 'permission' => 'roles.view', 'active' => ['roles.*']],
            ['label' => 'صندوق الاعتمادات', 'icon' => 'clipboard', 'route' => 'approvals.index', 'permission' => 'approvals.view', 'active' => ['approvals.index']],
            ['label' => 'تفويضات الاعتماد', 'icon' => 'users', 'route' => 'delegations.index', 'permission' => 'delegations.view', 'active' => ['delegations.*']],
            ['label' => 'سجل التدقيق', 'icon' => 'chart', 'route' => 'audit.index', 'permission' => 'audit.view', 'active' => ['audit.*']],
        ],
    ],
    [
        'key' => 'settings',
        'label' => 'الإعدادات',
        'icon' => 'settings',
        'items' => [
            ['label' => 'إعدادات الفرع', 'icon' => 'settings', 'route' => 'branch-settings.edit', 'permission' => 'branch_settings.view', 'active' => ['branch-settings.*']],
            ['label' => 'العملات', 'icon' => 'settings', 'route' => 'reference.index', 'params' => ['currencies'], 'permission' => 'settings.view', 'active' => ['reference.*'], 'active_param' => ['section', 'currencies']],
            ['label' => 'الضرائب', 'icon' => 'settings', 'route' => 'reference.index', 'params' => ['taxes'], 'permission' => 'taxes.view', 'active' => ['reference.*'], 'active_param' => ['section', 'taxes']],
            ['label' => 'الوحدات', 'icon' => 'settings', 'route' => 'reference.index', 'params' => ['units'], 'permission' => 'units.view', 'active' => ['reference.*'], 'active_param' => ['section', 'units']],
            ['label' => 'طرق الدفع', 'icon' => 'settings', 'route' => 'reference.index', 'params' => ['payment-methods'], 'permission' => 'payment_methods.view', 'active' => ['reference.*'], 'active_param' => ['section', 'payment-methods']],
            ['label' => 'ماركات السيارات', 'icon' => 'car', 'route' => 'reference.index', 'params' => ['vehicle-brands'], 'permission' => 'vehicle_references.view', 'active' => ['reference.*'], 'active_param' => ['section', 'vehicle-brands']],
            ['label' => 'موديلات السيارات', 'icon' => 'car', 'route' => 'reference.index', 'params' => ['vehicle-models'], 'permission' => 'vehicle_references.view', 'active' => ['reference.*'], 'active_param' => ['section', 'vehicle-models']],
            ['label' => 'أحجام السيارات', 'icon' => 'car', 'route' => 'reference.index', 'params' => ['vehicle-sizes'], 'permission' => 'vehicle_references.view', 'active' => ['reference.*'], 'active_param' => ['section', 'vehicle-sizes']],
            ['label' => 'أنواع السيارات', 'icon' => 'car', 'route' => 'reference.index', 'params' => ['vehicle-types'], 'permission' => 'vehicle_references.view', 'active' => ['reference.*'], 'active_param' => ['section', 'vehicle-types']],
            ['label' => 'السنوات المالية المرجعية', 'icon' => 'clock', 'route' => 'reference.index', 'params' => ['fiscal-years'], 'permission' => 'fiscal_years.view', 'active' => ['reference.*'], 'active_param' => ['section', 'fiscal-years']],
            ['label' => 'تسلسل أرقام المستندات', 'icon' => 'clipboard', 'route' => 'reference.index', 'params' => ['document-sequences'], 'permission' => 'document_sequences.view', 'active' => ['reference.*'], 'active_param' => ['section', 'document-sequences']],
            ['label' => 'السنوات المالية المحاسبية', 'icon' => 'clock', 'route' => 'accounting.fiscal-years.index', 'permission' => 'accounting.fiscal_years.view', 'active' => ['accounting.fiscal-years.*']],
            ['label' => 'إعدادات المحاسبة', 'icon' => 'settings', 'route' => 'accounting.settings.edit', 'permission' => 'accounting.settings.view', 'active' => ['accounting.settings.*', 'accounting.branch-settings.*']],
            ['label' => 'قوالب الترحيل', 'icon' => 'clipboard', 'route' => 'accounting.posting-profiles.index', 'permission' => 'accounting.posting_profiles.view', 'active' => ['accounting.posting-profiles.*']],
            ['label' => 'الأرصدة الافتتاحية', 'icon' => 'wallet', 'route' => 'accounting.opening-balances.index', 'permission' => 'accounting.opening_balances.view', 'active' => ['accounting.opening-balances.*']],
            ['label' => 'ربط الحسابات', 'icon' => 'settings', 'route' => 'accounting.mappings.index', 'permissions_any' => ['accounting.mappings.payment_methods', 'accounting.mappings.products'], 'active' => ['accounting.mappings.*']],
            ['label' => 'ربط وسائل الدفع', 'icon' => 'settings', 'route' => 'treasury.mappings.index', 'permission' => 'treasury.mappings.view', 'active' => ['treasury.mappings.*']],
            ['label' => 'ملفات تعريف الاستيراد', 'icon' => 'settings', 'route' => 'treasury.bank-statement-profiles.index', 'permission' => 'treasury.bank_statements.import', 'active' => ['treasury.bank-statement-profiles.*']],
            ['label' => 'قواعد المطابقة', 'icon' => 'settings', 'route' => 'treasury.matching-rules.index', 'permission' => 'treasury.matching_rules.view', 'active' => ['treasury.matching-rules.*']],
            ['label' => 'حدود الاعتماد', 'icon' => 'settings', 'route' => 'treasury.approval-limits.index', 'permission' => 'treasury.approval_limits.view', 'active' => ['treasury.approval-limits.*']],
        ],
    ],
];
