@extends('layouts.app')
@section('title',$supplier->name) @section('page-title',$supplier->name)
@section('content')
<div class="sw-page-actions"><a class="sw-btn sw-btn--secondary" href="{{ route('suppliers.edit',$supplier) }}">تعديل</a>@can('viewBalance',$supplier)<a class="sw-btn" href="{{ route('supplier-statements.show',$supplier) }}">كشف الحساب</a>@endcan</div>
<div class="sw-card"><div class="sw-detail-grid"><div><small>الكود</small><strong>{{ $supplier->supplier_code }}</strong></div><div><small>الحالة</small><strong>{{ $supplier->status }}</strong></div><div><small>الرقم الضريبي</small><strong>{{ $supplier->tax_number?:'—' }}</strong></div><div><small>شروط السداد</small><strong>{{ $supplier->payment_terms_days }} يوم</strong></div></div></div>
<div class="sw-card"><h2>جهات الاتصال</h2><table class="sw-table"><tbody>@foreach($supplier->contacts as $contact)<tr><td>{{ $contact->name }}</td><td>{{ $contact->phone }}</td><td>{{ $contact->is_primary?'أساسي':'' }}</td></tr>@endforeach</tbody></table>
<form class="sw-form" method="POST" action="{{ route('suppliers.contacts.store',$supplier) }}">@csrf <input name="name" required placeholder="الاسم"><input name="phone" placeholder="الهاتف"><label><input type="checkbox" name="is_primary" value="1"> أساسي</label><button class="sw-btn">إضافة</button></form></div>
<div class="sw-card"><h2>العناوين</h2><table class="sw-table"><tbody>@foreach($supplier->addresses as $address)<tr><td>{{ $address->address_type }}</td><td>{{ $address->address_line }}</td><td>{{ $address->is_primary?'أساسي':'' }}</td></tr>@endforeach</tbody></table>
<form class="sw-form" method="POST" action="{{ route('suppliers.addresses.store',$supplier) }}">@csrf <select name="address_type"><option value="billing">فوترة</option><option value="shipping">شحن</option><option value="office">مكتب</option></select><input name="address_line" required placeholder="العنوان"><label><input type="checkbox" name="is_primary" value="1"> أساسي</label><button class="sw-btn">إضافة</button></form></div>
<div class="sw-card"><h2>منتجات المورد</h2><table class="sw-table"><tbody>@foreach($supplier->products as $item)<tr><td>{{ $item->product->name }}</td><td>{{ $item->default_purchase_price }}</td><td>{{ $item->conversion_factor }}</td></tr>@endforeach</tbody></table>
<form class="sw-form" method="POST" action="{{ route('suppliers.products.store',$supplier) }}">@csrf <select name="product_id">@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }}</option>@endforeach</select><select name="purchase_unit_id">@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->name }}</option>@endforeach</select><input type="number" step=".000001" name="conversion_factor" value="1" required><input type="number" step=".0001" name="default_purchase_price" placeholder="السعر"><button class="sw-btn">حفظ</button></form></div>
@endsection
