@extends('layouts.app')
@section('title', 'تقارير المطابقة البنكية')
@section('page-title', 'تقارير المطابقة البنكية')
@section('content')
<div class="sw-card"><h3>ملخص الجلسات</h3><table class="sw-table"><thead><tr><th>الرقم</th><th>الفترة</th><th>الفرق</th><th>الحالة</th></tr></thead><tbody>@foreach($sessions as $session)<tr><td>{{ $session->session_number }}</td><td>{{ $session->date_from->toDateString() }} — {{ $session->date_to->toDateString() }}</td><td>{{ $session->difference }}</td><td>{{ $session->status }}</td></tr>@endforeach</tbody></table></div>
<div class="sw-card"><h3>حركات كشف البنك غير المطابقة</h3><table class="sw-table"><thead><tr><th>التاريخ</th><th>المرجع</th><th>الوصف</th><th>المتبقي</th></tr></thead><tbody>@foreach($unmatchedLines as $line)<tr><td>{{ $line->transaction_date->toDateString() }}</td><td>{{ $line->bank_reference }}</td><td>{{ $line->description }}</td><td>{{ $line->unmatched_amount }}</td></tr>@endforeach</tbody></table></div>
<div class="sw-card"><h3>حركات الدفاتر غير المطابقة</h3><table class="sw-table"><thead><tr><th>التاريخ</th><th>القيد</th><th>المرجع</th><th>المتبقي</th></tr></thead><tbody>@foreach($unmatchedBook as $line)<tr><td>{{ $line->entry->posting_date->toDateString() }}</td><td>{{ $line->entry->journal_number }}</td><td>{{ $line->reference }}</td><td>{{ $line->reconciliation_unmatched_amount }}</td></tr>@endforeach</tbody></table></div>
<div class="sw-card"><h3>الأسطر المكررة</h3><table class="sw-table"><thead><tr><th>التاريخ</th><th>المرجع</th><th>الوصف</th><th>الأصل</th></tr></thead><tbody>@foreach($duplicateLines as $line)<tr><td>{{ $line->transaction_date->toDateString() }}</td><td>{{ $line->bank_reference }}</td><td>{{ $line->description }}</td><td>{{ $line->duplicate_of_id }}</td></tr>@endforeach</tbody></table></div>
<div class="sw-card"><h3>سجل تسويات البنك</h3><table class="sw-table"><thead><tr><th>الرقم</th><th>التاريخ</th><th>النوع</th><th>القيمة</th><th>الحالة</th></tr></thead><tbody>@foreach($adjustments as $adjustment)<tr><td>{{ $adjustment->document_number }}</td><td>{{ $adjustment->adjustment_date->toDateString() }}</td><td>{{ $adjustment->adjustment_type }}</td><td>{{ $adjustment->amount }}</td><td>{{ $adjustment->status }}</td></tr>@endforeach</tbody></table></div>
@endsection
